// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Infrastructure;

namespace WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190709122525_IPAddressAdded")]
    partial class IPAddressAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Model.Transcription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfMeeting");

                    b.Property<string>("MeetingPlatform");

                    b.Property<string>("TranscriptionARN");

                    b.Property<string>("UserIPAddress");

                    b.HasKey("Id");

                    b.ToTable("Transcription");
                });

            modelBuilder.Entity("Common.Model.TranscriptionUser", b =>
                {
                    b.Property<int>("TranscriptionId");

                    b.Property<int>("UserId");

                    b.HasKey("TranscriptionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TranscriptionUser");
                });

            modelBuilder.Entity("Common.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Common.Model.TranscriptionUser", b =>
                {
                    b.HasOne("Common.Model.Transcription", "Transcription")
                        .WithMany("TranscriptionUsers")
                        .HasForeignKey("TranscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Common.Model.User", "User")
                        .WithMany("TranscriptionUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
